export default `
:root{color-scheme:dark;font-family:Inter,Arial,"Noto Sans SC",sans-serif;background:#171717;color:#f7f4ef}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}
button,input,textarea{font:inherit}button,.button{border:0;border-radius:8px;background:#ee7900;color:#fff;padding:.7rem 1.1rem;font-weight:700;cursor:pointer;display:inline-block}
.button.secondary,button.secondary{background:#333}.button.danger,button.danger{background:#9e312b}
header{background:#101010;border-bottom:1px solid #333;padding:1rem max(1rem,calc((100vw - 1120px)/2));display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}
header strong{font-size:1.4rem}.dot{color:#ee7900}nav,.language, .actions{display:flex;align-items:center;gap:.8rem;flex-wrap:wrap}nav a:hover,.active{color:#ff850c}
main{max-width:1120px;margin:0 auto;padding:3.4rem 1rem 5rem}h1{font-size:clamp(2.2rem,5vw,3.8rem);margin:.2rem 0 1rem}h2{margin:2rem 0 1rem}h3{margin:.2rem 0}.lead{color:#c9c9c9;font-size:1.15rem;line-height:1.75;max-width:850px}
.eyebrow{color:#ff850c;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.muted{color:#aaa}.notice{padding:1rem;border-left:4px solid #ee7900;background:#302317;margin:1.3rem 0}.error{border-left-color:#d34d43;background:#351c1a}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1.1rem;margin:2rem 0}.card,.panel{background:#242424;border:1px solid #414141;border-radius:16px;padding:1.35rem}.card{display:block;min-height:160px}.card:hover{border-color:#ee7900;text-decoration:none}.card p{color:#c9c9c9;line-height:1.6}.card img{width:100%;height:190px;object-fit:cover;border-radius:10px;margin-bottom:.8rem}.tag{display:inline-block;border:1px solid #704118;border-radius:20px;color:#ff9d36;padding:.25rem .7rem;font-size:.8rem;margin:.3rem .3rem .3rem 0}
.hero-image{width:100%;max-height:520px;object-fit:contain;background:#111;border-radius:14px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.gallery img{width:100%;height:240px;object-fit:cover;border-radius:10px}.prose{font-size:1.08rem;line-height:1.9;max-width:850px}.prose p{white-space:pre-wrap}
form{margin:0}.field{margin:1rem 0}.field label,.field legend{font-weight:700;display:block;margin-bottom:.45rem}.field input[type=text],.field input[type=number],.field textarea{width:100%;padding:.8rem;background:#171717;border:1px solid #555;border-radius:8px;color:#fff}.field textarea{min-height:100px;resize:vertical}.field textarea.body{min-height:230px}.check{display:block;margin:.5rem 0}.check input{margin-right:.55rem}fieldset{border:1px solid #555;border-radius:12px;margin:1.3rem 0;padding:1rem}fieldset legend{color:#ff9d36;padding:0 .4rem}.admin-item{display:flex;justify-content:space-between;gap:1rem;align-items:center;border-bottom:1px solid #444;padding:1rem 0}.admin-item:last-child{border:0}.photo-admin{display:flex;align-items:center;gap:1rem;margin:1rem 0;flex-wrap:wrap}.photo-admin img{width:140px;height:100px;object-fit:cover;border-radius:8px}footer{border-top:1px solid #333;padding:2rem 1rem;text-align:center;color:#999}
@media(max-width:620px){main{padding-top:2rem}.admin-item{align-items:start;flex-direction:column}}
`;
