export default `
:root{color-scheme:dark;font-family:Inter,Arial,"Noto Sans SC",sans-serif;background:#171717;color:#f7f4ef}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}
button,input,textarea{font:inherit}button,.button{border:0;border-radius:8px;background:#ee7900;color:#fff;padding:.7rem 1.1rem;font-weight:700;cursor:pointer;display:inline-block}
.button.secondary,button.secondary{background:#333}.button.danger,button.danger{background:#9e312b}
.nav-logout{background:none;padding:0;font-weight:400;color:inherit}.nav-logout:hover{color:#ff850c;text-decoration:underline}
header{background:#101010;border-bottom:1px solid #333;padding:1rem max(1rem,calc((100vw - 1120px)/2));display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}
header strong{font-size:1.4rem}.dot{color:#ee7900}nav,.language, .actions{display:flex;align-items:center;gap:.8rem;flex-wrap:wrap}nav a:hover,.active{color:#ff850c}
.language{padding-left:.65rem;border-left:1px solid rgba(232,93,4,.22)}.language-menu{position:relative}.language-menu summary{display:inline-flex;align-items:center;gap:.25rem;min-width:3.2rem;padding:.28rem .7rem;border-radius:999px;background:rgba(232,93,4,.1);color:#f7f4ef;font-size:.76rem;font-weight:800;line-height:1;white-space:nowrap;cursor:pointer;list-style:none}.language-menu summary::-webkit-details-marker{display:none}.language-menu summary::after{content:'▾';color:#ee7900;font-size:.68rem}.language-options{position:absolute;top:calc(100% + .65rem);right:0;z-index:120;display:grid;min-width:8.8rem;padding:.45rem;border:1px solid #414141;border-radius:8px;background:#fff;box-shadow:0 16px 45px rgba(0,0,0,.25)}.language-options a{display:block;padding:.55rem .65rem;border-radius:6px;color:#1a1a1a;font-size:.82rem}.language-options a.active,.language-options a:hover{background:rgba(232,93,4,.1);color:#e85d04;text-decoration:none}
main{max-width:1120px;margin:0 auto;padding:3.4rem 1rem 5rem}h1{font-size:clamp(2.2rem,5vw,3.8rem);margin:.2rem 0 1rem}h2{margin:2rem 0 1rem}h3{margin:.2rem 0}.lead{color:#c9c9c9;font-size:1.15rem;line-height:1.75;max-width:850px}
.eyebrow{color:#ff850c;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.muted{color:#aaa}.notice{padding:1rem;border-left:4px solid #ee7900;background:#302317;margin:1.3rem 0}.error{border-left-color:#d34d43;background:#351c1a}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1.1rem;margin:2rem 0}.card,.panel{background:#242424;border:1px solid #414141;border-radius:16px;padding:1.35rem}.card{display:block;min-height:160px}.card:hover{border-color:#ee7900;text-decoration:none}.card p{color:#c9c9c9;line-height:1.6}.card img{width:100%;height:190px;object-fit:cover;border-radius:10px;margin-bottom:.8rem}.tag{display:inline-block;border:1px solid #704118;border-radius:20px;color:#ff9d36;padding:.25rem .7rem;font-size:.8rem;margin:.3rem .3rem .3rem 0}
.section-links{justify-content:flex-start;margin:1.5rem 0 2rem}.section-links a{border:1px solid #704118;border-radius:20px;padding:.45rem .8rem}.overview-entry{margin:1rem 0 1.5rem}.overview-entry.focused{border-color:#ee7900}.overview-entry .grid{margin:1rem 0 0}.overview-entry h3 a:hover{color:#ff9d36}
.hero-image{width:100%;max-height:520px;object-fit:contain;background:#111;border-radius:14px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.gallery img{width:100%;height:240px;object-fit:cover;border-radius:10px}.prose{font-size:1.08rem;line-height:1.9;max-width:850px}.prose p{white-space:pre-wrap}
form{margin:0}.field{margin:1rem 0}.field label,.field legend{font-weight:700;display:block;margin-bottom:.45rem}.field input[type=text],.field input[type=email],.field input[type=password],.field input[type=number],.field textarea{width:100%;padding:.8rem;background:#171717;border:1px solid #555;border-radius:8px;color:#fff}.field textarea{min-height:100px;resize:vertical}.field textarea.body{min-height:230px}.check{display:block;margin:.5rem 0}.check input{margin-right:.55rem}fieldset{border:1px solid #555;border-radius:12px;margin:1.3rem 0;padding:1rem}fieldset legend{color:#ff9d36;padding:0 .4rem}.admin-item{display:flex;justify-content:space-between;gap:1rem;align-items:center;border-bottom:1px solid #444;padding:1rem 0}.admin-item:last-child{border:0}.photo-admin{display:flex;align-items:center;gap:1rem;margin:1rem 0;flex-wrap:wrap}.photo-admin img{width:140px;height:100px;object-fit:cover;border-radius:8px}.login-page main{min-height:calc(100vh - 90px);display:grid;place-items:center}.login-panel{width:min(100%,440px);padding:2rem;border:1px solid #414141;border-radius:18px;background:#242424}.login-panel h1{font-size:clamp(1.8rem,4vw,2.5rem)}.login-panel form button{width:100%}.login-panel>p:last-child{margin:1.5rem 0 0;color:#ff9d36}.login-panel code{overflow-wrap:anywhere}footer{border-top:1px solid #333;padding:2rem 1rem;text-align:center;color:#999}
.login-page main{grid-template-columns:minmax(0,1fr);width:100%}.login-panel{min-width:0}
@media(max-width:620px){main{padding-top:2rem}.admin-item{align-items:start;flex-direction:column}}
`;
